name: Run Python scripts on commit

on:
  push:
    branches:
      - master  # You can change this to the branch you want to trigger the actions

jobs:
  run-scripts:
    name: Run Python scripts
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - name: Run first script
        run: python render_static_pages.py  

      - name: Run second script
        run: python update_notices.py 
        
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Automated modifications"
          git push
      # - name: Add & Commit
      #   uses: EndBug/add-and-commit@v9.1.4
      #   with:
      #     message : Rebuilt site [vercel]
        
            

                    
      # - name: Git Auto Commit
      #   uses: stefanzweifel/git-auto-commit-action@v5.0.0
      #   with:
      #     commit_message: Rebuilt site [vercel]
      #     skip_dirty_check: false  
